version: '3.8'

networks:
  moco:
    driver: bridge

services:
  api:
    container_name: api
    image: mocoapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53084:80"
    depends_on:
      - keycloak
      - db
    networks:
      - moco

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: [ 'start-dev' ]
    ports:
      - "8081:8080"

    networks:
      - moco

  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - "3307:3306"

    networks:
      - moco
