name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  
        dotnet-version: [7.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (Nuxt 3)
        run: |
          cd Source/WebApp
          npm ci

      - name: Build Nuxt 3 app
        run: |
          cd Source/WebApp
          npm run build
      
      - name: Upload Nuxt build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: Moco/Source/WebApp/.output
          retention-days: 30 

      - name: Set up .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies (.NET)
        run: dotnet restore

      - name: Build .NET API
        run: dotnet publish --configuration Release --output ./publish --no-restore

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet7-publish
          path: Moco/FastApiTest/publish/
          retention-days: 30 
